import type {RosterCell,Staff,Violation,Ward,Swap} from '../entities';
const hours=(s:'D'|'E'|'N'|'L'|null)=>s==='L'||!s?0:8;
export function validateRoster(cells:RosterCell[],staff:Staff[],ward:Ward,weekDates:string[]):Violation[]{const out:Violation[]=[]; const byStaff=new Map(staff.map(s=>[s.id,s]));
for(const s of staff){const mine=cells.filter(c=>c.staffId===s.id); for(const d of weekDates){const day=mine.filter(c=>c.date===d&&c.shift&&c.shift!=='L');if(day.length>1)out.push({rule:'R1',severity:'ERROR',staffId:s.id,date:d,message:`${s.name} has more than one shift on ${d}.`}); const cell=mine.find(c=>c.date===d&&c.shift); if(cell?.shift&&cell.shift!=='L'&&s.leaveDates.includes(d))out.push({rule:'R5',severity:'ERROR',staffId:s.id,date:d,message:`${s.name} is on approved leave on ${d}.`}); if(cell?.shift==='N'&&ward.code==='ICU'&&(!s.icuCertExpiry||s.icuCertExpiry<=d))out.push({rule:'R4',severity:'ERROR',staffId:s.id,date:d,message:`${s.name} has no valid ICU certification for ${d}.`}); }
const worked=mine.filter(c=>c.shift&&c.shift!=='L').sort((a,b)=>a.date.localeCompare(b.date)); let total=worked.reduce((n,c)=>n+hours(c.shift),0); if(total>48)out.push({rule:'R3',severity:'ERROR',staffId:s.id,message:`${s.name} has ${total} weekly hours, above 48.`}); else if(total>40)out.push({rule:'R3',severity:'WARNING',staffId:s.id,message:`${s.name} has ${total} weekly hours, above 40.`});
let nights=0; for(const c of worked){if(c.shift==='N'){nights++;if(nights>3)out.push({rule:'R6',severity:'WARNING',staffId:s.id,date:c.date,message:`${s.name} has more than 3 consecutive Night shifts.`});}else nights=0;}
for(let i=1;i<worked.length;i++){const a=worked[i-1],b=worked[i]; const gap=hoursBetween(a,b); if(gap<11)out.push({rule:'R2',severity:'ERROR',staffId:s.id,date:b.date,message:`${s.name} has only ${gap}h rest between ${a.shift} (${a.date}) and ${b.shift} (${b.date}).`});}}
for(const d of weekDates)for(const sh of ['D','E','N'] as const){const assigned=cells.filter(c=>c.date===d&&c.shift===sh).map(c=>byStaff.get(c.staffId)).filter(Boolean) as Staff[]; const req=ward.requirements[sh]; const seniors=assigned.filter(s=>s.grade==='SENIOR').length;if(assigned.length<req.total||seniors<req.seniors)out.push({rule:'R7',severity:'WARNING',date:d,message:`${ward.name} ${sh} coverage on ${d}: ${assigned.length}/${req.total} nurses, ${seniors}/${req.seniors} seniors.`});}
return out;}
function hoursBetween(a:RosterCell,b:RosterCell){const start=new Date(`${a.date}T${a.shift==='N'?'23:00':a.shift==='E'?'15:00':'07:00'}:00`);const end=new Date(`${b.date}T${b.shift==='N'?'23:00':b.shift==='E'?'15:00':'07:00'}:00`); if(a.shift==='N')start.setHours(start.getHours()+8); else start.setHours(start.getHours()+8); return Math.round((end.getTime()-start.getTime())/3600000);}
export function validateSwap(swap:Swap,cells:RosterCell[],staff:Staff[],ward:Ward,weekDates:string[]):Violation[]{const next=cells.map(c=>({...c}));const from=next.find(c=>c.staffId===swap.fromStaffId&&c.date===swap.date&&c.shift===swap.shift);const to=next.find(c=>c.staffId===swap.toStaffId&&c.date===swap.date);if(from)from.staffId=swap.toStaffId;if(to)to.shift=null; const all=validateRoster(next,staff,ward,weekDates);return all.filter(v=>v.staffId===swap.toStaffId||v.staffId===swap.fromStaffId);}
